version: "2"
services:
  server:
    build: ./server
    links:
      - mongo
      - fake-services
    depends_on:
      - mongo
    volumes:
      - "./server/:/src/"
    ports:
      - "4000:3000"

  # frontend:
  #   build: ./frontend
  #   links:
  #     - server
  #   depends_on:
  #     - server
  #   volumes:
  #     - "./frontend/src:/src/src"
  #     - "./frontend/public:/src/public"
  #   ports:
  #     - "3000:3000"

  fake-services:
    build: ./fake-services
    volumes:
      - "./fake-services/:/src/"
    environment:
      - GMAPS_ACCESS_KEY=${GMAPS_ACCESS_KEY}
    ports:
      - "3030:3000"

  mongo:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27018:27017
