version: "2"
services:
  server:
    build: ./server
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - "./server/:/src/"
    ports:
      - "4000:3000"


  frontend:
    build: ./frontend
    links:
      - server
    depends_on:
      - server
    volumes:
      - "./frontend/:/src/"
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27018:27017
